security.protocol=${KAFKA_CLIENT_SECURITY_PROTOCOL}
sasl.mechanism=${KAFKA_CLIENT_SASL_MECHANISM}
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_CLIENT_SASL_USERNAME}" password="${KAFKA_CLIENT_SASL_PASSWORD}";
